# Generated by Django 2.1.7 on 2019-08-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnae',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
    ]
