# Generated by Django 2.1.7 on 2019-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogrs', '0002_auto_20190815_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuo',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
    ]
