# Generated by Django 2.1.7 on 2019-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogrs', '0004_auto_20190829_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='responsavel_juridico',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='prestadorservico',
            name='nome_fantasia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestadorservico',
            name='razao_social',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
