# Generated by Django 2.1.7 on 2019-08-15 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto_em', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('assunto', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=60, verbose_name='Descrição')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aberto', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechado', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.PROTECT, to='chamados.Chamado')),
                ('user', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['data'],
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.Tipo'),
        ),
    ]
