# Generated by Django 2.1.7 on 2019-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='assunto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
    ]
