# Generated by Django 2.1.7 on 2019-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20190815_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechado em'),
        ),
    ]
